import { Event } from "@/types/event";
import fetchedEventsRaw from "@/data/fetched-events.json";

export const DELHI_NCR_EVENTS: Event[] = [
  {
    id: "evt-001",
    name: "India AI Summit 2026",
    category: "tech-ai",
    date: "2026-06-05",
    endDate: "2026-06-06",
    time: "09:00 AM",
    venue: "Bharat Mandapam",
    address: "Pragati Maidan, Ring Road",
    area: "New Delhi",
    description:
      "India's largest AI & emerging technology summit bringing together policy makers, enterprise leaders, and AI researchers. Sessions cover Generative AI, AI governance, automation in BFSI, healthcare AI, and the future of work.",
    highlights: [
      "Keynotes from 50+ global AI leaders",
      "Live demos of cutting-edge AI models",
      "AI policy roundtable with government officials",
      "Startup pitch competition with ₹1 Cr prize pool",
      "Workshops on LLMs, RAG, and AI agents",
    ],
    organizer: "NASSCOM & Ministry of Electronics & IT",
    expectedAttendees: "5,000+",
    format: "in-person",
    ticket: {
      available: false,
      status: "closed",
      price: "₹2,999 – ₹15,000",
      link: "https://www.nasscom.in/events",
      platform: "NASSCOM Portal",
      registrationDeadline: "2026-06-03",
      tiers: [
        { name: "Student Pass", price: "₹2,999", status: "sold-out", perks: ["Summit access", "Lunch"] },
        { name: "Professional", price: "₹7,999", status: "sold-out", perks: ["All sessions", "Workshop access", "Networking lunch"] },
        { name: "VIP", price: "₹15,000", status: "sold-out", perks: ["Front-row seating", "Speaker meet & greet", "Premium lounge"] },
      ],
      bookingSteps: [
        "Visit nasscom.in/events",
        "Click 'India AI Summit 2026'",
        "Select your ticket tier",
        "Fill in attendee details",
        "Pay via UPI/Card/Net Banking",
        "Receive e-ticket on email",
      ],
    },
    tags: ["AI", "Machine Learning", "GenAI", "Policy", "Startups"],
    featured: true,
    sourceUrl: "https://www.nasscom.in/events",
  },
  {
    id: "evt-002",
    name: "Delhi Fintech Festival 2026",
    category: "finance",
    date: "2026-06-12",
    endDate: "2026-06-13",
    time: "10:00 AM",
    venue: "The Leela Palace",
    address: "Diplomatic Enclave, Chanakyapuri",
    area: "New Delhi",
    description:
      "A premier fintech gathering exploring digital payments, UPI innovation, CBDC, crypto regulations, and the future of Indian financial services. Features panel discussions with RBI officials, banking CEOs, and fintech founders.",
    highlights: [
      "RBI Governor address on CBDC roadmap",
      "UPI 3.0 feature showcase",
      "Panel: Neobanks vs Traditional Banks",
      "Regulatory sandbox demos",
      "Networking lunch with 200+ CFOs and CXOs",
    ],
    organizer: "India Fintech Forum",
    expectedAttendees: "1,500+",
    format: "in-person",
    ticket: {
      available: true,
      status: "few-left",
      price: "₹4,999 – ₹25,000",
      link: "https://www.indiafintech.com",
      platform: "Eventbrite",
      registrationDeadline: "2026-06-11",
      tiers: [
        { name: "Standard", price: "₹4,999", status: "sold-out", perks: ["All sessions", "Exhibition access"] },
        { name: "Premium", price: "₹12,000", status: "few-left", perks: ["Premium seating", "Networking lunch", "Workshop access"] },
        { name: "Executive", price: "₹25,000", status: "available", perks: ["VIP lounge", "1:1 meeting slots", "Gala dinner invite"] },
      ],
      bookingSteps: [
        "Go to indiafintech.com",
        "Navigate to 'Delhi Fintech Festival'",
        "Choose ticket category (Standard/Premium/Executive)",
        "Enter name, email, company details",
        "Complete payment on Eventbrite",
        "Download ticket PDF from confirmation email",
      ],
    },
    tags: ["Fintech", "UPI", "CBDC", "Digital Payments", "Banking"],
    featured: true,
    sourceUrl: "https://www.indiafintech.com",
  },
  {
    id: "evt-003",
    name: "Google I/O Extended Delhi NCR",
    category: "tech-ai",
    date: "2026-06-08",
    time: "10:00 AM",
    venue: "Google India Office",
    address: "Tower B, DLF Cyber City",
    area: "Gurugram",
    description:
      "Community-driven Google I/O Extended event for Delhi NCR developers. Watch Google I/O sessions live, attend local talks on Android, Firebase, Google Cloud, and Gemini API. Hands-on codelabs and networking.",
    highlights: [
      "Live stream of Google I/O keynote",
      "Gemini API workshop for developers",
      "Android 15 deep dive session",
      "Firebase + GenAI integration lab",
      "Community project showcase",
    ],
    organizer: "GDG Delhi & GDG Gurugram",
    expectedAttendees: "500+",
    format: "in-person",
    ticket: {
      available: false,
      status: "closed",
      price: "Free",
      link: "https://gdg.community.dev/gdg-new-delhi",
      platform: "GDG Community",
      registrationDeadline: "2026-06-06",
      bookingSteps: [
        "Open gdg.community.dev/gdg-new-delhi",
        "Sign in with your Google account",
        "Click 'RSVP' on the event",
        "Check your email for confirmation",
      ],
    },
    tags: ["Google", "Android", "Firebase", "Gemini", "GDG"],
    sourceUrl: "https://gdg.community.dev/gdg-new-delhi",
  },
  {
    id: "evt-004",
    name: "McKinsey Leadership Forum: Future of Indian Business",
    category: "consulting",
    date: "2026-06-18",
    time: "09:30 AM",
    venue: "The Oberoi",
    address: "Dr. Zakir Hussain Marg",
    area: "New Delhi",
    description:
      "An exclusive half-day forum where McKinsey senior partners share research insights on the next decade of Indian business transformation — covering supply chain resilience, ESG mandates, talent transformation, and digital strategy.",
    highlights: [
      "McKinsey Global Institute India report launch",
      "CEO panel: Digital transformation lessons",
      "Workshop: Building resilient organizations",
      "1:1 advisory sessions with McKinsey partners",
      "Curated networking dinner",
    ],
    organizer: "McKinsey & Company India",
    expectedAttendees: "150 (invite-only + limited open seats)",
    format: "in-person",
    ticket: {
      available: true,
      status: "few-left",
      price: "₹12,000 (open seats)",
      link: "https://www.mckinsey.com/india/events",
      platform: "McKinsey Events Portal",
      registrationDeadline: "2026-06-16",
      tiers: [
        { name: "Open Seat", price: "₹12,000", status: "few-left", perks: ["Forum access", "Networking dinner"] },
      ],
      bookingSteps: [
        "Visit mckinsey.com/india/events",
        "Find 'Leadership Forum' event listing",
        "Click 'Request Seat' for open category",
        "Submit professional profile and LinkedIn URL",
        "Receive confirmation within 48 hours",
        "Pay registration fee upon approval",
      ],
    },
    tags: ["Consulting", "Leadership", "Strategy", "Business", "ESG"],
    sourceUrl: "https://www.mckinsey.com/india",
  },
  {
    id: "evt-005",
    name: "Coldplay: Music of the Spheres World Tour",
    category: "entertainment",
    date: "2026-11-19",
    endDate: "2026-11-21",
    time: "06:00 PM",
    venue: "Jawaharlal Nehru Stadium",
    address: "Lodhi Road",
    area: "New Delhi",
    description:
      "Coldplay returns to India with their record-breaking Music of the Spheres World Tour. Three nights of spectacular live performance featuring their greatest hits from Yellow to My Universe, accompanied by breathtaking LED wristbands, fireworks, and an immersive audio-visual spectacle.",
    highlights: [
      "Three nights of full-length concerts",
      "LED wristband experience for all attendees",
      "New album 'Moon Music' songs performed live",
      "Sustainable stage powered by renewable energy",
      "Opening acts: local Indian artists",
    ],
    organizer: "BookMyShow Live & Live Nation India",
    expectedAttendees: "70,000 per night",
    format: "in-person",
    ticket: {
      available: true,
      status: "selling-fast",
      price: "₹2,500 – ₹35,000",
      link: "https://in.bookmyshow.com",
      platform: "BookMyShow",
      tiers: [
        { name: "South Stand", price: "₹2,500", status: "sold-out" },
        { name: "North Stand", price: "₹4,000", status: "selling-fast" },
        { name: "Floor Standing", price: "₹9,500", status: "selling-fast" },
        { name: "Lounge", price: "₹35,000", status: "available", perks: ["Premium lounge", "Complimentary drinks", "Best view"] },
      ],
      bookingSteps: [
        "Open BookMyShow app or bookmyshow.com",
        "Search 'Coldplay Delhi'",
        "Select your preferred date (19/20/21 Nov)",
        "Choose ticket category and number of seats",
        "Apply any promo code if available",
        "Pay via UPI, credit card, or wallet",
        "Save e-ticket — you'll need it at entry",
      ],
    },
    tags: ["Concert", "Coldplay", "Music", "Live", "International"],
    featured: true,
    sourceUrl: "https://in.bookmyshow.com",
  },
  {
    id: "evt-006",
    name: "TEDxConnaught Place: Rebuild & Rise",
    category: "knowledge",
    date: "2026-06-22",
    time: "10:00 AM",
    venue: "Siri Fort Auditorium",
    address: "August Kranti Marg, Siri Fort",
    area: "New Delhi",
    description:
      "A full-day independently organized TED event featuring 12 remarkable speakers sharing ideas worth spreading. This year's theme 'Rebuild & Rise' covers mental health, climate action, entrepreneurship, art in the digital age, and indigenous knowledge systems.",
    highlights: [
      "12 curated speakers across disciplines",
      "Live performance: Delhi classical music ensemble",
      "Idea marketplace: interactive exhibits",
      "Speaker Q&A and meet-and-greet sessions",
      "Official TEDx talk recording for global release",
    ],
    organizer: "TEDxConnaught Place",
    expectedAttendees: "800+",
    format: "in-person",
    ticket: {
      available: true,
      status: "selling-fast",
      price: "₹1,500 – ₹4,000",
      link: "https://www.ted.com/tedx/events",
      platform: "TED Official Website",
      registrationDeadline: "2026-06-20",
      tiers: [
        { name: "General", price: "₹1,500", status: "selling-fast" },
        { name: "Premium", price: "₹3,000", status: "available", perks: ["Priority seating", "Networking access"] },
        { name: "Patron", price: "₹4,000", status: "available", perks: ["Front row", "Speaker dinner invite", "TEDx merchandise"] },
      ],
      bookingSteps: [
        "Go to ted.com/tedx/events",
        "Search for 'TEDxConnaught Place'",
        "Click 'Attend' and choose your tier",
        "Create/log in to your TED account",
        "Complete payment",
        "Receive e-ticket via email",
      ],
    },
    tags: ["TEDx", "Ideas", "Innovation", "Mental Health", "Climate"],
    sourceUrl: "https://www.ted.com/tedx/events",
  },
  {
    id: "evt-007",
    name: "AWS re:Invent Roadshow Delhi",
    category: "tech-ai",
    date: "2026-06-25",
    time: "09:00 AM",
    venue: "Pullman Hotel",
    address: "Asset 1, Aerocity",
    area: "New Delhi",
    description:
      "Amazon Web Services brings its annual re:Invent content to Delhi with localized sessions on cloud architecture, serverless computing, machine learning on AWS, and AWS GenAI services. Includes hands-on labs and AWS certification exam vouchers.",
    highlights: [
      "Amazon Bedrock & Claude API workshop",
      "Serverless architecture best practices",
      "AWS Well-Architected Framework review labs",
      "Free AWS certification exam vouchers",
      "1:1 cloud architect office hours",
    ],
    organizer: "Amazon Web Services India",
    expectedAttendees: "1,000+",
    format: "in-person",
    ticket: {
      available: true,
      status: "free",
      price: "Free (registration required)",
      link: "https://aws.amazon.com/events/india",
      platform: "AWS Events Portal",
      registrationDeadline: "2026-06-23",
      bookingSteps: [
        "Visit aws.amazon.com/events/india",
        "Find 're:Invent Roadshow Delhi' listing",
        "Click 'Register Now'",
        "Sign in with your AWS account (or create one free)",
        "Fill in professional details",
        "Select sessions you want to attend",
        "Submit — confirmation email arrives instantly",
      ],
    },
    tags: ["AWS", "Cloud", "GenAI", "Serverless", "DevOps"],
    sourceUrl: "https://aws.amazon.com/events/india",
  },
  {
    id: "evt-008",
    name: "Startup Delhi: Investor Connect Summit",
    category: "networking",
    date: "2026-06-15",
    time: "11:00 AM",
    venue: "91springboard",
    address: "Okhla Industrial Estate, Phase III",
    area: "New Delhi",
    description:
      "A curated startup-investor matchmaking summit bringing 200+ funded startups together with 80+ active VCs, angel investors, and family offices. Focused sectors: D2C, SaaS, climate tech, and deep tech. Includes pitch sessions, funding masterclasses, and closed networking.",
    highlights: [
      "80+ VCs and angel investors in one room",
      "10-minute 1:1 investor pitch slots",
      "Panel: What investors look for in 2026",
      "Term sheet negotiation workshop",
      "Startup of the year awards ceremony",
    ],
    organizer: "Startup Delhi & iStart India",
    expectedAttendees: "600+",
    format: "in-person",
    ticket: {
      available: true,
      status: "available",
      price: "₹999 (startups) / ₹5,000 (investors)",
      link: "https://www.startupindia.gov.in/events",
      platform: "Startup India Portal",
      registrationDeadline: "2026-06-14",
      tiers: [
        { name: "Startup Pass", price: "₹999", status: "available", perks: ["Summit access", "Pitch slot eligibility"] },
        { name: "Investor Pass", price: "₹5,000", status: "available", perks: ["Premium lounge", "Priority pitch viewing", "Deal room access"] },
      ],
      bookingSteps: [
        "Go to startupindia.gov.in/events",
        "Click on 'Investor Connect Summit'",
        "Choose 'Startup' or 'Investor' category",
        "Fill in company/fund details",
        "Upload pitch deck (startups) or investment thesis (investors)",
        "Pay and receive confirmation",
      ],
    },
    tags: ["Startup", "VC", "Funding", "Pitch", "Entrepreneur"],
    sourceUrl: "https://www.startupindia.gov.in",
  },
  {
    id: "evt-009",
    name: "NH7 Weekender Delhi",
    category: "entertainment",
    date: "2026-07-05",
    endDate: "2026-07-06",
    time: "03:00 PM",
    venue: "HUDA Ground",
    address: "Sector 29",
    area: "Gurugram",
    description:
      "India's happiest music festival returns to Delhi NCR with three stages of indie, electronic, hip-hop, and world music across two days. Featuring 40+ artists, a curated food court, artisan market, and immersive art installations.",
    highlights: [
      "40+ artists across 3 stages",
      "Headline acts: Nucleya, Prateek Kuhad, Divine",
      "International DJ night (Stage 3)",
      "Artisan food court with 30+ stalls",
      "Interactive art zone & workshops",
    ],
    organizer: "OML Entertainment",
    expectedAttendees: "25,000+ (both days)",
    format: "in-person",
    ticket: {
      available: true,
      status: "available",
      price: "₹1,200 – ₹8,000",
      link: "https://insider.in/nh7-weekender",
      platform: "Paytm Insider",
      tiers: [
        { name: "Single Day", price: "₹1,200", status: "available" },
        { name: "Weekend Pass", price: "₹2,000", status: "available", perks: ["Both days access"] },
        { name: "VIP Weekend", price: "₹8,000", status: "available", perks: ["Both days", "VIP viewing area", "Backstage access", "Complimentary drinks"] },
      ],
      bookingSteps: [
        "Download Paytm Insider app or visit insider.in",
        "Search 'NH7 Weekender Delhi'",
        "Choose Single Day or Weekend Pass",
        "Select number of tickets (max 6 per transaction)",
        "Pay via UPI, card, or Paytm wallet",
        "Show QR code from app at entry gate",
      ],
    },
    tags: ["Music Festival", "Indie", "Electronic", "Hip-Hop", "NH7"],
    featured: true,
    sourceUrl: "https://insider.in",
  },
  {
    id: "evt-010",
    name: "CFA Institute Research Challenge — Delhi Finals",
    category: "finance",
    date: "2026-06-10",
    time: "09:00 AM",
    venue: "MDI Gurugram",
    address: "Mehrauli Road, Sukhrali",
    area: "Gurugram",
    description:
      "The prestigious CFA Research Challenge Delhi regional finals where top B-school teams present equity research reports. Open to observers from the investment community. Features expert feedback from CFA charterholders and industry mentors.",
    highlights: [
      "Top 8 teams compete for national berth",
      "Live equity research presentations",
      "Expert panel critique by CFA charterholders",
      "Networking with Delhi investment community",
      "Post-event reception",
    ],
    organizer: "CFA Society India",
    expectedAttendees: "300+",
    format: "in-person",
    ticket: {
      available: false,
      status: "closed",
      price: "Free (observer registration)",
      link: "https://www.cfasocietyindia.org/events",
      platform: "CFA Society India",
      registrationDeadline: "2026-06-08",
      bookingSteps: [
        "Visit cfasocietyindia.org/events",
        "Click 'Research Challenge Finals'",
        "Register as 'Observer'",
        "Enter CFA member ID or professional details",
        "Receive confirmation email with venue pass",
      ],
    },
    tags: ["CFA", "Finance", "Equity Research", "Investment", "B-School"],
    sourceUrl: "https://www.cfasocietyindia.org",
  },
  {
    id: "evt-011",
    name: "Microsoft AI Tour: Delhi",
    category: "tech-ai",
    date: "2026-07-02",
    time: "09:00 AM",
    venue: "ITPO Convention Centre",
    address: "Pragati Maidan",
    area: "New Delhi",
    description:
      "Microsoft's global AI Tour comes to Delhi — a one-day immersive event showcasing how Microsoft Copilot, Azure OpenAI, and Microsoft Fabric are transforming enterprise productivity. Featuring technical sessions, demos, and hands-on labs.",
    highlights: [
      "Azure OpenAI + Copilot Studio workshops",
      "Microsoft Fabric for enterprise analytics",
      "Security in the age of AI",
      "GitHub Copilot for developer productivity",
      "Hands-on labs with real enterprise scenarios",
    ],
    organizer: "Microsoft India",
    expectedAttendees: "2,000+",
    format: "in-person",
    ticket: {
      available: true,
      status: "free",
      price: "Free (registration required)",
      link: "https://aitour.microsoft.com/india",
      platform: "Microsoft Events",
      registrationDeadline: "2026-06-30",
      bookingSteps: [
        "Visit aitour.microsoft.com",
        "Select 'Delhi' from location list",
        "Sign in with Microsoft account",
        "Choose sessions and labs to attend",
        "Register — instant confirmation via email",
      ],
    },
    tags: ["Microsoft", "Copilot", "Azure", "AI", "Enterprise"],
    sourceUrl: "https://aitour.microsoft.com",
  },
  {
    id: "evt-012",
    name: "Management Consulting Case Competition — IIM Delhi",
    category: "consulting",
    date: "2026-06-28",
    endDate: "2026-06-29",
    time: "08:00 AM",
    venue: "IIM Rohtak Delhi NCR Campus",
    address: "Plot No. 7, Sector 16-A",
    area: "Gurugram",
    description:
      "A two-day open management consulting case competition where cross-functional teams solve real business problems presented by McKinsey, BCG, and Bain. Open to working professionals and students. Cash prizes and internship offers for winners.",
    highlights: [
      "Real cases from MBB firms (McKinsey, BCG, Bain)",
      "Expert mentors from top consulting firms",
      "Framework workshops: MECE, issue trees",
      "Final presentations to consulting partners",
      "Cash prize pool of ₹3,00,000",
    ],
    organizer: "Consult Club, IIM Rohtak",
    expectedAttendees: "200+ participants",
    format: "in-person",
    ticket: {
      available: true,
      status: "available",
      price: "₹500 per team",
      link: "https://www.iimrohtak.ac.in/events",
      platform: "IIM Rohtak Portal",
      registrationDeadline: "2026-06-25",
      bookingSteps: [
        "Visit iimrohtak.ac.in/events",
        "Click 'Case Competition' registration link",
        "Form a team of 3–4 members",
        "Submit team details and college/company info",
        "Pay ₹500 team registration fee online",
        "Receive case brief 24 hours before event",
      ],
    },
    tags: ["Consulting", "Case Study", "MBB", "Strategy", "Competition"],
    sourceUrl: "https://www.iimrohtak.ac.in",
  },
  {
    id: "evt-013",
    name: "International Book Fair — New Delhi",
    category: "knowledge",
    date: "2026-07-10",
    endDate: "2026-07-18",
    time: "10:00 AM",
    venue: "Pragati Maidan",
    address: "Mathura Road, Pragati Maidan",
    area: "New Delhi",
    description:
      "Asia's largest book fair returns with 1,400+ publishers from 40 countries. Features author talks, book launches, literary debates, children's pavilion, and themed pavilions covering science, history, business, and fiction. A 9-day celebration of reading and ideas.",
    highlights: [
      "1,400+ publishers from 40 countries",
      "100+ author talks and book launches",
      "International publisher rights exchange",
      "Children's Book Pavilion with activities",
      "National Book Trust discounts up to 50%",
    ],
    organizer: "National Book Trust, India",
    expectedAttendees: "3,00,000+ (across 9 days)",
    format: "in-person",
    ticket: {
      available: true,
      status: "available",
      price: "₹30 (entry) / Free for children under 12",
      link: "https://www.ndwbf.org",
      platform: "Spot entry / Online booking",
      bookingSteps: [
        "Buy ticket at the gate (₹30 cash/UPI)",
        "Or pre-book online at ndwbf.org",
        "Children under 12 enter free",
        "No registration deadline — walk-in welcome all 9 days",
      ],
    },
    tags: ["Books", "Literature", "Authors", "Publishing", "Learning"],
    sourceUrl: "https://www.ndwbf.org",
  },
  {
    id: "evt-014",
    name: "Automation & Robotics Expo 2026",
    category: "tech-ai",
    date: "2026-07-15",
    endDate: "2026-07-17",
    time: "10:00 AM",
    venue: "Yashobhoomi (IICC)",
    address: "Sector 25, Dwarka",
    area: "New Delhi",
    description:
      "India's definitive industrial automation and robotics expo showcasing the latest in manufacturing automation, cobots, AI-driven quality control, warehouse robotics, and Industry 4.0 solutions. 300+ exhibitors from 25 countries.",
    highlights: [
      "300+ exhibitors from 25 countries",
      "Live robot demos on the showfloor",
      "Industry 4.0 conference track",
      "Smart factory of the future showcase",
      "Startup pavilion: Deep tech robotics",
    ],
    organizer: "Messe Düsseldorf India",
    expectedAttendees: "20,000+",
    format: "in-person",
    ticket: {
      available: true,
      status: "free",
      price: "Free (pre-registration) / ₹500 at gate",
      link: "https://www.india.messeduesseldorf.in",
      platform: "Official Expo Website",
      registrationDeadline: "2026-07-14",
      bookingSteps: [
        "Visit india.messeduesseldorf.in",
        "Click 'Visitor Registration'",
        "Fill in professional details and industry",
        "Submit — free badge mailed to your email",
        "Print badge or show QR at entry",
        "Or pay ₹500 at gate for walk-in entry",
      ],
    },
    tags: ["Robotics", "Automation", "Industry 4.0", "Manufacturing", "IoT"],
    sourceUrl: "https://www.india.messeduesseldorf.in",
  },
  {
    id: "evt-015",
    name: "Diljit Dosanjh: Dil-Luminati Tour — Delhi",
    category: "entertainment",
    date: "2026-08-14",
    time: "07:00 PM",
    venue: "Jawaharlal Nehru Stadium",
    address: "Lodhi Road",
    area: "New Delhi",
    description:
      "Punjabi superstar Diljit Dosanjh's mega Dil-Luminati concert in Delhi — a 3-hour extravaganza of his biggest hits spanning his entire career, accompanied by live musicians, state-of-the-art light production, and a surprise collaboration guest.",
    highlights: [
      "3-hour live concert performance",
      "Full live band with 20+ musicians",
      "LED screen experience spanning 100m stage",
      "Songs from all albums including G.O.A.T and Ghost",
      "Special Independence Day edition",
    ],
    organizer: "BookMyShow Live",
    expectedAttendees: "55,000",
    format: "in-person",
    ticket: {
      available: true,
      status: "selling-fast",
      price: "₹999 – ₹20,000",
      link: "https://in.bookmyshow.com",
      platform: "BookMyShow",
      tiers: [
        { name: "Silver Stand", price: "₹999", status: "sold-out" },
        { name: "Gold Stand", price: "₹2,999", status: "selling-fast" },
        { name: "Platinum", price: "₹7,999", status: "available", perks: ["Close to stage", "Fast-track entry"] },
        { name: "Fan Pit", price: "₹20,000", status: "available", perks: ["Right next to stage", "Merch included", "Early entry"] },
      ],
      bookingSteps: [
        "Open BookMyShow app or bookmyshow.com",
        "Search 'Diljit Delhi'",
        "Select category and number of tickets",
        "Complete payment via UPI/Card",
        "E-ticket sent to your email and app",
      ],
    },
    tags: ["Concert", "Diljit", "Punjabi", "Bollywood", "Music"],
    sourceUrl: "https://in.bookmyshow.com",
  },
  {
    id: "evt-016",
    name: "Blockchain & Web3 India Conference",
    category: "tech-ai",
    date: "2026-06-20",
    time: "09:30 AM",
    venue: "Radisson Blu Plaza",
    address: "National Highway 8",
    area: "Gurugram",
    description:
      "India's leading Web3 conference covering DeFi, NFTs, blockchain for enterprise, cryptocurrency regulation under India's Digital Asset Bill, and the future of decentralized applications. Features fireside chats with founders of leading Indian Web3 startups.",
    highlights: [
      "India crypto regulation update from SEBI",
      "DeFi protocol deep-dives",
      "Enterprise blockchain use cases",
      "Web3 startup pitch: ₹50L prize",
      "Networking with 500+ Web3 builders",
    ],
    organizer: "Bharat Web3 Association",
    expectedAttendees: "1,200+",
    format: "in-person",
    ticket: {
      available: true,
      status: "available",
      price: "₹1,499 – ₹8,000",
      link: "https://www.bharatweb3.org/events",
      platform: "Eventbrite",
      registrationDeadline: "2026-06-19",
      tiers: [
        { name: "Community", price: "₹1,499", status: "available", perks: ["Conference access"] },
        { name: "Builder", price: "₹3,999", status: "available", perks: ["Conference + hackathon", "Lunch included"] },
        { name: "Whale", price: "₹8,000", status: "available", perks: ["VIP access", "Private networking", "Investor meet"] },
      ],
      bookingSteps: [
        "Go to bharatweb3.org/events",
        "Click 'Register' on the conference",
        "Select your pass tier",
        "Complete Eventbrite checkout",
        "Receive e-ticket and Discord invite link",
      ],
    },
    tags: ["Web3", "Blockchain", "DeFi", "Crypto", "NFT"],
    sourceUrl: "https://www.bharatweb3.org",
  },
];

const FETCHED_EVENTS = (fetchedEventsRaw as unknown as Event[]).map((e) => ({
  ...e,
  ticket: {
    ...e.ticket,
    status: e.ticket.status ?? (e.ticket.available ? "available" : "closed"),
  },
}));

export const ALL_EVENTS: Event[] = [
  ...DELHI_NCR_EVENTS,
  ...FETCHED_EVENTS.filter(
    (fe) => !DELHI_NCR_EVENTS.some((e) => e.name.toLowerCase() === fe.name.toLowerCase())
  ),
];

export function getEventsByCategory(category: string, events: Event[]) {
  if (category === "all") return events;
  return events.filter((e) => e.category === category);
}

export function getUpcomingEvents(events: Event[]) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return events
    .filter((e) => new Date(e.date) >= today)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
}

export function getFeaturedEvents(events: Event[]) {
  return events.filter((e) => e.featured);
}

export function searchEvents(query: string, events: Event[]) {
  const q = query.toLowerCase();
  return events.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.tags.some((t) => t.toLowerCase().includes(q)) ||
      e.area.toLowerCase().includes(q) ||
      e.venue.toLowerCase().includes(q)
  );
}
