import { Event } from "@/types/event";
import fetchedEventsRaw from "@/data/fetched-events.json";

export const DELHI_NCR_EVENTS: Event[] = [
  {
    id: "evt-001",
    name: "India AI Summit 2026",
    category: "tech-ai",
    date: "2026-06-05",
    endDate: "2026-06-06",
    time: "09:00 AM",
    venue: "Bharat Mandapam",
    address: "Pragati Maidan, Ring Road",
    area: "New Delhi",
    description:
      "India's largest AI & emerging technology summit bringing together policy makers, enterprise leaders, and AI researchers. Sessions cover Generative AI, AI governance, automation in BFSI, healthcare AI, and the future of work.",
    highlights: [
      "Keynotes from 50+ global AI leaders",
      "Live demos of cutting-edge AI models",
      "AI policy roundtable with government officials",
      "Startup pitch competition with ₹1 Cr prize pool",
      "Workshops on LLMs, RAG, and AI agents",
    ],
    organizer: "NASSCOM & Ministry of Electronics & IT",
    expectedAttendees: "5,000+",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹2,999 – ₹15,000",
      link: "https://www.nasscom.in/events",
      platform: "NASSCOM Portal",
    },
    tags: ["AI", "Machine Learning", "GenAI", "Policy", "Startups"],
    featured: true,
    sourceUrl: "https://www.nasscom.in/events",
  },
  {
    id: "evt-002",
    name: "Delhi Fintech Festival 2026",
    category: "finance",
    date: "2026-06-12",
    endDate: "2026-06-13",
    time: "10:00 AM",
    venue: "The Leela Palace",
    address: "Diplomatic Enclave, Chanakyapuri",
    area: "New Delhi",
    description:
      "A premier fintech gathering exploring digital payments, UPI innovation, CBDC, crypto regulations, and the future of Indian financial services. Features panel discussions with RBI officials, banking CEOs, and fintech founders.",
    highlights: [
      "RBI Governor address on CBDC roadmap",
      "UPI 3.0 feature showcase",
      "Panel: Neobanks vs Traditional Banks",
      "Regulatory sandbox demos",
      "Networking lunch with 200+ CFOs and CXOs",
    ],
    organizer: "India Fintech Forum",
    expectedAttendees: "1,500+",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹4,999 – ₹25,000",
      link: "https://www.indiafintech.com",
      platform: "Eventbrite",
    },
    tags: ["Fintech", "UPI", "CBDC", "Digital Payments", "Banking"],
    featured: true,
    sourceUrl: "https://www.indiafintech.com",
  },
  {
    id: "evt-003",
    name: "Google I/O Extended Delhi NCR",
    category: "tech-ai",
    date: "2026-06-08",
    time: "10:00 AM",
    venue: "Google India Office",
    address: "Tower B, DLF Cyber City",
    area: "Gurugram",
    description:
      "Community-driven Google I/O Extended event for Delhi NCR developers. Watch Google I/O sessions live, attend local talks on Android, Firebase, Google Cloud, and Gemini API. Hands-on codelabs and networking.",
    highlights: [
      "Live stream of Google I/O keynote",
      "Gemini API workshop for developers",
      "Android 15 deep dive session",
      "Firebase + GenAI integration lab",
      "Community project showcase",
    ],
    organizer: "GDG Delhi & GDG Gurugram",
    expectedAttendees: "500+",
    format: "in-person",
    ticket: {
      available: true,
      price: "Free",
      link: "https://gdg.community.dev/gdg-new-delhi",
      platform: "GDG Community",
    },
    tags: ["Google", "Android", "Firebase", "Gemini", "GDG"],
    sourceUrl: "https://gdg.community.dev/gdg-new-delhi",
  },
  {
    id: "evt-004",
    name: "McKinsey Leadership Forum: Future of Indian Business",
    category: "consulting",
    date: "2026-06-18",
    time: "09:30 AM",
    venue: "The Oberoi",
    address: "Dr. Zakir Hussain Marg",
    area: "New Delhi",
    description:
      "An exclusive half-day forum where McKinsey senior partners share research insights on the next decade of Indian business transformation — covering supply chain resilience, ESG mandates, talent transformation, and digital strategy.",
    highlights: [
      "McKinsey Global Institute India report launch",
      "CEO panel: Digital transformation lessons",
      "Workshop: Building resilient organizations",
      "1:1 advisory sessions with McKinsey partners",
      "Curated networking dinner",
    ],
    organizer: "McKinsey & Company India",
    expectedAttendees: "150 (invite-only + limited open seats)",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹12,000 (open seats)",
      link: "https://www.mckinsey.com/india/events",
      platform: "McKinsey Events Portal",
    },
    tags: ["Consulting", "Leadership", "Strategy", "Business", "ESG"],
    sourceUrl: "https://www.mckinsey.com/india",
  },
  {
    id: "evt-005",
    name: "Coldplay: Music of the Spheres World Tour",
    category: "entertainment",
    date: "2026-11-19",
    endDate: "2026-11-21",
    time: "06:00 PM",
    venue: "Jawaharlal Nehru Stadium",
    address: "Lodhi Road",
    area: "New Delhi",
    description:
      "Coldplay returns to India with their record-breaking Music of the Spheres World Tour. Three nights of spectacular live performance featuring their greatest hits from Yellow to My Universe, accompanied by breathtaking LED wristbands, fireworks, and an immersive audio-visual spectacle.",
    highlights: [
      "Three nights of full-length concerts",
      "LED wristband experience for all attendees",
      "New album 'Moon Music' songs performed live",
      "Sustainable stage powered by renewable energy",
      "Opening acts: local Indian artists",
    ],
    organizer: "BookMyShow Live & Live Nation India",
    expectedAttendees: "70,000 per night",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹2,500 – ₹35,000",
      link: "https://in.bookmyshow.com",
      platform: "BookMyShow",
    },
    tags: ["Concert", "Coldplay", "Music", "Live", "International"],
    featured: true,
    sourceUrl: "https://in.bookmyshow.com",
  },
  {
    id: "evt-006",
    name: "TEDxConnaught Place: Rebuild & Rise",
    category: "knowledge",
    date: "2026-06-22",
    time: "10:00 AM",
    venue: "Siri Fort Auditorium",
    address: "August Kranti Marg, Siri Fort",
    area: "New Delhi",
    description:
      "A full-day independently organized TED event featuring 12 remarkable speakers sharing ideas worth spreading. This year's theme 'Rebuild & Rise' covers mental health, climate action, entrepreneurship, art in the digital age, and indigenous knowledge systems.",
    highlights: [
      "12 curated speakers across disciplines",
      "Live performance: Delhi classical music ensemble",
      "Idea marketplace: interactive exhibits",
      "Speaker Q&A and meet-and-greet sessions",
      "Official TEDx talk recording for global release",
    ],
    organizer: "TEDxConnaught Place",
    expectedAttendees: "800+",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹1,500 – ₹4,000",
      link: "https://www.ted.com/tedx/events",
      platform: "TED Official Website",
    },
    tags: ["TEDx", "Ideas", "Innovation", "Mental Health", "Climate"],
    sourceUrl: "https://www.ted.com/tedx/events",
  },
  {
    id: "evt-007",
    name: "AWS re:Invent Roadshow Delhi",
    category: "tech-ai",
    date: "2026-06-25",
    time: "09:00 AM",
    venue: "Pullman Hotel",
    address: "Asset 1, Aerocity",
    area: "New Delhi",
    description:
      "Amazon Web Services brings its annual re:Invent content to Delhi with localized sessions on cloud architecture, serverless computing, machine learning on AWS, and AWS GenAI services. Includes hands-on labs and AWS certification exam vouchers.",
    highlights: [
      "Amazon Bedrock & Claude API workshop",
      "Serverless architecture best practices",
      "AWS Well-Architected Framework review labs",
      "Free AWS certification exam vouchers",
      "1:1 cloud architect office hours",
    ],
    organizer: "Amazon Web Services India",
    expectedAttendees: "1,000+",
    format: "in-person",
    ticket: {
      available: true,
      price: "Free (registration required)",
      link: "https://aws.amazon.com/events/india",
      platform: "AWS Events Portal",
    },
    tags: ["AWS", "Cloud", "GenAI", "Serverless", "DevOps"],
    sourceUrl: "https://aws.amazon.com/events/india",
  },
  {
    id: "evt-008",
    name: "Startup Delhi: Investor Connect Summit",
    category: "networking",
    date: "2026-06-15",
    time: "11:00 AM",
    venue: "91springboard",
    address: "Okhla Industrial Estate, Phase III",
    area: "New Delhi",
    description:
      "A curated startup-investor matchmaking summit bringing 200+ funded startups together with 80+ active VCs, angel investors, and family offices. Focused sectors: D2C, SaaS, climate tech, and deep tech. Includes pitch sessions, funding masterclasses, and closed networking.",
    highlights: [
      "80+ VCs and angel investors in one room",
      "10-minute 1:1 investor pitch slots",
      "Panel: What investors look for in 2026",
      "Term sheet negotiation workshop",
      "Startup of the year awards ceremony",
    ],
    organizer: "Startup Delhi & iStart India",
    expectedAttendees: "600+",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹999 (startups) / ₹5,000 (investors)",
      link: "https://www.startupindia.gov.in/events",
      platform: "Startup India Portal",
    },
    tags: ["Startup", "VC", "Funding", "Pitch", "Entrepreneur"],
    sourceUrl: "https://www.startupindia.gov.in",
  },
  {
    id: "evt-009",
    name: "NH7 Weekender Delhi",
    category: "entertainment",
    date: "2026-07-05",
    endDate: "2026-07-06",
    time: "03:00 PM",
    venue: "HUDA Ground",
    address: "Sector 29",
    area: "Gurugram",
    description:
      "India's happiest music festival returns to Delhi NCR with three stages of indie, electronic, hip-hop, and world music across two days. Featuring 40+ artists, a curated food court, artisan market, and immersive art installations.",
    highlights: [
      "40+ artists across 3 stages",
      "Headline acts: Nucleya, Prateek Kuhad, Divine",
      "International DJ night (Stage 3)",
      "Artisan food court with 30+ stalls",
      "Interactive art zone & workshops",
    ],
    organizer: "OML Entertainment",
    expectedAttendees: "25,000+ (both days)",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹1,200 – ₹8,000",
      link: "https://insider.in/nh7-weekender",
      platform: "Paytm Insider",
    },
    tags: ["Music Festival", "Indie", "Electronic", "Hip-Hop", "NH7"],
    featured: true,
    sourceUrl: "https://insider.in",
  },
  {
    id: "evt-010",
    name: "CFA Institute Research Challenge — Delhi Finals",
    category: "finance",
    date: "2026-06-10",
    time: "09:00 AM",
    venue: "MDI Gurugram",
    address: "Mehrauli Road, Sukhrali",
    area: "Gurugram",
    description:
      "The prestigious CFA Research Challenge Delhi regional finals where top B-school teams present equity research reports. Open to observers from the investment community. Features expert feedback from CFA charterholders and industry mentors.",
    highlights: [
      "Top 8 teams compete for national berth",
      "Live equity research presentations",
      "Expert panel critique by CFA charterholders",
      "Networking with Delhi investment community",
      "Post-event reception",
    ],
    organizer: "CFA Society India",
    expectedAttendees: "300+",
    format: "in-person",
    ticket: {
      available: true,
      price: "Free (observer registration)",
      link: "https://www.cfasocietyindia.org/events",
      platform: "CFA Society India",
    },
    tags: ["CFA", "Finance", "Equity Research", "Investment", "B-School"],
    sourceUrl: "https://www.cfasocietyindia.org",
  },
  {
    id: "evt-011",
    name: "Microsoft AI Tour: Delhi",
    category: "tech-ai",
    date: "2026-07-02",
    time: "09:00 AM",
    venue: "HITEX Exhibition Center",
    address: "Appa Junction, near IIIT Hyderabad (Delhi Edition at ITPO)",
    area: "New Delhi",
    description:
      "Microsoft's global AI Tour comes to Delhi — a one-day immersive event showcasing how Microsoft Copilot, Azure OpenAI, and Microsoft Fabric are transforming enterprise productivity. Featuring technical sessions, demos, and hands-on labs.",
    highlights: [
      "Azure OpenAI + Copilot Studio workshops",
      "Microsoft Fabric for enterprise analytics",
      "Security in the age of AI",
      "GitHub Copilot for developer productivity",
      "Hands-on labs with real enterprise scenarios",
    ],
    organizer: "Microsoft India",
    expectedAttendees: "2,000+",
    format: "in-person",
    ticket: {
      available: true,
      price: "Free (registration required)",
      link: "https://aitour.microsoft.com/india",
      platform: "Microsoft Events",
    },
    tags: ["Microsoft", "Copilot", "Azure", "AI", "Enterprise"],
    sourceUrl: "https://aitour.microsoft.com",
  },
  {
    id: "evt-012",
    name: "Management Consulting Case Competition — IIM Delhi",
    category: "consulting",
    date: "2026-06-28",
    endDate: "2026-06-29",
    time: "08:00 AM",
    venue: "IIM Rohtak Delhi NCR Campus",
    address: "Plot No. 7, Sector 16-A",
    area: "Gurugram",
    description:
      "A two-day open management consulting case competition where cross-functional teams solve real business problems presented by McKinsey, BCG, and Bain. Open to working professionals and students. Cash prizes and internship offers for winners.",
    highlights: [
      "Real cases from MBB firms (McKinsey, BCG, Bain)",
      "Expert mentors from top consulting firms",
      "Framework workshops: MECE, issue trees",
      "Final presentations to consulting partners",
      "Cash prize pool of ₹3,00,000",
    ],
    organizer: "Consult Club, IIM Rohtak",
    expectedAttendees: "200+ participants",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹500 per team",
      link: "https://www.iimrohtak.ac.in/events",
      platform: "IIM Rohtak Portal",
    },
    tags: ["Consulting", "Case Study", "MBB", "Strategy", "Competition"],
    sourceUrl: "https://www.iimrohtak.ac.in",
  },
  {
    id: "evt-013",
    name: "International Book Fair — New Delhi",
    category: "knowledge",
    date: "2026-07-10",
    endDate: "2026-07-18",
    time: "10:00 AM",
    venue: "Pragati Maidan",
    address: "Mathura Road, Pragati Maidan",
    area: "New Delhi",
    description:
      "Asia's largest book fair returns with 1,400+ publishers from 40 countries. Features author talks, book launches, literary debates, children's pavilion, and themed pavilions covering science, history, business, and fiction. A 9-day celebration of reading and ideas.",
    highlights: [
      "1,400+ publishers from 40 countries",
      "100+ author talks and book launches",
      "International publisher rights exchange",
      "Children's Book Pavilion with activities",
      "National Book Trust discounts up to 50%",
    ],
    organizer: "National Book Trust, India",
    expectedAttendees: "3,00,000+ (across 9 days)",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹30 (entry) / Free for children under 12",
      link: "https://www.ndwbf.org",
      platform: "Spot entry / Online booking",
    },
    tags: ["Books", "Literature", "Authors", "Publishing", "Learning"],
    sourceUrl: "https://www.ndwbf.org",
  },
  {
    id: "evt-014",
    name: "Automation & Robotics Expo 2026",
    category: "tech-ai",
    date: "2026-07-15",
    endDate: "2026-07-17",
    time: "10:00 AM",
    venue: "Yashobhoomi (IICC)",
    address: "Sector 25, Dwarka",
    area: "New Delhi",
    description:
      "India's definitive industrial automation and robotics expo showcasing the latest in manufacturing automation, cobots, AI-driven quality control, warehouse robotics, and Industry 4.0 solutions. 300+ exhibitors from 25 countries.",
    highlights: [
      "300+ exhibitors from 25 countries",
      "Live robot demos on the showfloor",
      "Industry 4.0 conference track",
      "Smart factory of the future showcase",
      "Startup pavilion: Deep tech robotics",
    ],
    organizer: "Messe Düsseldorf India",
    expectedAttendees: "20,000+",
    format: "in-person",
    ticket: {
      available: true,
      price: "Free (pre-registration) / ₹500 at gate",
      link: "https://www.india.messeduesseldorf.in",
      platform: "Official Expo Website",
    },
    tags: ["Robotics", "Automation", "Industry 4.0", "Manufacturing", "IoT"],
    sourceUrl: "https://www.india.messeduesseldorf.in",
  },
  {
    id: "evt-015",
    name: "Diljit Dosanjh: Dil-Luminati Tour — Delhi",
    category: "entertainment",
    date: "2026-08-14",
    time: "07:00 PM",
    venue: "Jawaharlal Nehru Stadium",
    address: "Lodhi Road",
    area: "New Delhi",
    description:
      "Punjabi superstar Diljit Dosanjh's mega Dil-Luminati concert in Delhi — a 3-hour extravaganza of his biggest hits spanning his entire career, accompanied by live musicians, state-of-the-art light production, and a surprise collaboration guest.",
    highlights: [
      "3-hour live concert performance",
      "Full live band with 20+ musicians",
      "LED screen experience spanning 100m stage",
      "Songs from all albums including G.O.A.T and Ghost",
      "Special Independence Day edition",
    ],
    organizer: "BookMyShow Live",
    expectedAttendees: "55,000",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹999 – ₹20,000",
      link: "https://in.bookmyshow.com",
      platform: "BookMyShow",
    },
    tags: ["Concert", "Diljit", "Punjabi", "Bollywood", "Music"],
    sourceUrl: "https://in.bookmyshow.com",
  },
  {
    id: "evt-016",
    name: "Blockchain & Web3 India Conference",
    category: "tech-ai",
    date: "2026-06-20",
    time: "09:30 AM",
    venue: "Radisson Blu Plaza",
    address: "National Highway 8",
    area: "Gurugram",
    description:
      "India's leading Web3 conference covering DeFi, NFTs, blockchain for enterprise, cryptocurrency regulation under India's Digital Asset Bill, and the future of decentralized applications. Features fireside chats with founders of leading Indian Web3 startups.",
    highlights: [
      "India crypto regulation update from SEBI",
      "DeFi protocol deep-dives",
      "Enterprise blockchain use cases",
      "Web3 startup pitch: ₹50L prize",
      "Networking with 500+ Web3 builders",
    ],
    organizer: "Bharat Web3 Association",
    expectedAttendees: "1,200+",
    format: "in-person",
    ticket: {
      available: true,
      price: "₹1,499 – ₹8,000",
      link: "https://www.bharatweb3.org/events",
      platform: "Eventbrite",
    },
    tags: ["Web3", "Blockchain", "DeFi", "Crypto", "NFT"],
    sourceUrl: "https://www.bharatweb3.org",
  },
];

const FETCHED_EVENTS = fetchedEventsRaw as Event[];

export const ALL_EVENTS: Event[] = [
  ...DELHI_NCR_EVENTS,
  ...FETCHED_EVENTS.filter(
    (fe) => !DELHI_NCR_EVENTS.some((e) => e.name.toLowerCase() === fe.name.toLowerCase())
  ),
];

export function getEventsByCategory(category: string, events: Event[]) {
  if (category === "all") return events;
  return events.filter((e) => e.category === category);
}

export function getUpcomingEvents(events: Event[]) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return events
    .filter((e) => new Date(e.date) >= today)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
}

export function getFeaturedEvents(events: Event[]) {
  return events.filter((e) => e.featured);
}

export function searchEvents(query: string, events: Event[]) {
  const q = query.toLowerCase();
  return events.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.tags.some((t) => t.toLowerCase().includes(q)) ||
      e.area.toLowerCase().includes(q) ||
      e.venue.toLowerCase().includes(q)
  );
}
